/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class NeuralRouter {
  constructor(modelPath: string, tokenizerPath: string)
  route(text: string): Array<number>
}
